### PR TITLE
Use PACKAGE_PREFIX_DIR rather than hard coded ROCM_PATH for finding the config files

### PR DESCRIPTION
**Pull request by raramakr**

### CODE REVIEW

**Comment by jrmadsen** [comment]
@raramakr please place `${ROCPROFSDK_PACKAGE_PREFIX_DIR}` before the hardcoded paths instead of replacing them. Your changes incorrectly assume that all the packages will always be installed under the same prefix, some package managers like spack have unique paths for each package.

**Review by jrmadsen — APPROVED** [review]
See https://github.com/ROCm/rocprofiler-sdk/pull/18#issuecomment-2370359275

**Review by jrmadsen — CHANGES_REQUESTED** [review]
See https://github.com/ROCm/rocprofiler-sdk/pull/18#issuecomment-2370359275

**Comment by raramakr** [comment]
> @raramakr please place `${ROCPROFSDK_PACKAGE_PREFIX_DIR}` before the hardcoded paths instead of replacing them. Your changes incorrectly assume that all the packages will always be installed under the same prefix, some package managers like spack have unique paths for each package.

HI  @jrmadsen , The patch was raised to remove the hard coded paths. To make ROCm relocatable , need to get rid of hard coded paths.
Even If each package have unique paths(not sure it applies to ROCm in spack) , having a hard coded path like /opt/rocm-ver will not help to find the package

**Comment by jrmadsen** [comment]
> HI @jrmadsen , The patch was raised to remove the hard coded paths. To make ROCm relocatable , need to get rid of hard coded paths. Even If each package have unique paths(not sure it applies to ROCm in spack) , having a hard coded path like /opt/rocm-ver will not help to find the package

Even as it is, this is relocatable, these “hard coded paths” are configured from where the build found these packages. They exist to help ensure that the install tree find_package, with no additional hints (e.g. `CMAKE_PREFIX_PATH`, `<PackageName>_DIR`), falls back to searching for the package where the build of rocprofiler-SDK found the packages. If these paths don’t exist in these locations, they are simply ignored. If you review the [config search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#full-signature) you can see the HINTS and PATHS are the 4th option — these paths are nothing more than fallbacks.

**Comment by raramakr** [comment]
Closing the PR . After discussion will raise a new PR in internal branch

**Pull request closed without merging**
